In [2]:
import pyspark
import pandas as pd
import pyspark.pandas as ps
from pyspark.sql import SparkSession

/Users/ale/Proyectos/envs/pyspark_env/lib/python3.11/site-packages/pyspark/pandas/__init__.py:50: UserWarning: 'PYARROW_IGNORE_TIMEZONE' environment variable was not set. It is required to set this environment variable to '1' in both driver and executor sides if you use pyarrow>=2.0.0. pandas-on-Spark will set it for you but it does not work if there is a Spark context already launched.
  warnings.warn(

In [3]:
spark = SparkSession.builder.getOrCreate()

25/07/18 11:41:49 WARN Utils: Your hostname, MacBook-Pro-de-ale.local resolves to a loopback address: 127.0.0.1; using 192.168.100.14 instead (on interface en0)
25/07/18 11:41:49 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
25/07/18 11:41:52 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

### Cargar dataset: world happinnes report

1. Exploración de datos
2. Eliminar vacíos

In [19]:
data = ps.read_csv('datasets/world-happiness-report.csv')
data.head(10)

/Users/ale/Proyectos/envs/pyspark_env/lib/python3.11/site-packages/pyspark/pandas/utils.py:1016: PandasAPIOnSparkAdviceWarning: If `index_col` is not specified for `read_csv`, the default index is attached which can cause additional overhead.
  warnings.warn(message, PandasAPIOnSparkAdviceWarning)

  Country name  year  Life Ladder  Log GDP per capita  Social support  Healthy life expectancy at birth  Freedom to make life choices  Generosity  Perceptions of corruption  Positive affect  Negative affect
0  Afghanistan  2008        3.724               7.370           0.451                             50.80                         0.718       0.168                      0.882            0.518            0.258
1  Afghanistan  2009        4.402               7.540           0.552                             51.20                         0.679       0.190                      0.850            0.584            0.237
2  Afghanistan  2010        4.758               7.647           0.539                             51.60                         0.600       0.121                      0.707            0.618            0.275
3  Afghanistan  2011        3.832               7.620           0.521                             51.92                         0.496       0.162                      0.731            0.611            0.267
4  Afghanistan  2012        3.783               7.705           0.521                             52.24                         0.531       0.236                      0.776            0.710            0.268
5  Afghanistan  2013        3.572               7.725           0.484                             52.56                         0.578       0.061                      0.823            0.621            0.273
6  Afghanistan  2014        3.131               7.718           0.526                             52.88                         0.509       0.104                      0.871            0.532            0.375
7  Afghanistan  2015        3.983               7.702           0.529                             53.20                         0.389       0.080                      0.881            0.554            0.339
8  Afghanistan  2016        4.220               7.697           0.559                             53.00                         0.523       0.042                      0.793            0.565            0.348
9  Afghanistan  2017        2.662               7.697           0.491                             52.80                         0.427      -0.121                      0.954            0.496            0.371

In [20]:
data.info()

<class 'pyspark.pandas.frame.DataFrame'>
Int64Index: 1949 entries, 0 to 1948
Data columns (total 11 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Country name                      1949 non-null   object
 1   year                              1949 non-null   int32
 2   Life Ladder                       1949 non-null   float64
 3   Log GDP per capita                1913 non-null   float64
 4   Social support                    1936 non-null   float64
 5   Healthy life expectancy at birth  1894 non-null   float64
 6   Freedom to make life choices      1917 non-null   float64
 7   Generosity                        1860 non-null   float64
 8   Perceptions of corruption         1839 non-null   float64
 9   Positive affect                   1927 non-null   float64
 10  Negative affect                   1933 non-null   float64
dtypes: float64(9), int32(1), object(1)

In [21]:
data.dtypes

Country name                         object
year                                  int32
Life Ladder                         float64
Log GDP per capita                  float64
Social support                      float64
Healthy life expectancy at birth    float64
Freedom to make life choices        float64
Generosity                          float64
Perceptions of corruption           float64
Positive affect                     float64
Negative affect                     float64
dtype: object

In [22]:
data.count()

Country name                        1949
year                                1949
Life Ladder                         1949
Log GDP per capita                  1913
Social support                      1936
Healthy life expectancy at birth    1894
Freedom to make life choices        1917
Generosity                          1860
Perceptions of corruption           1839
Positive affect                     1927
Negative affect                     1933
dtype: int64

In [23]:
data = data.dropna(how='any')
data.count()

Country name                        1708
year                                1708
Life Ladder                         1708
Log GDP per capita                  1708
Social support                      1708
Healthy life expectancy at birth    1708
Freedom to make life choices        1708
Generosity                          1708
Perceptions of corruption           1708
Positive affect                     1708
Negative affect                     1708
dtype: int64

Agrupar por país y mostrar las ocurrencias

In [24]:
country_data = data.groupby('Country name').size().reset_index(name='Country')
country_data

                 Country name  Country
0                        Chad       14
1                    Paraguay       13
2                      Russia       15
3                       Yemen        7
4                     Senegal       14
5                      Sweden       14
6                      Guyana        1
7                 Philippines       14
8                    Djibouti        3
9                    Malaysia       12
10                  Singapore       12
11                     Turkey       14
12                     Malawi       12
13                       Iraq       11
14                    Germany       13
15                    Comoros        6
16                Afghanistan       12
17                   Cambodia       12
18                Ivory Coast        9
19                     Jordan        2
20                     Rwanda       11
21                      Sudan        5
22                     France       14
23                     Greece       13
24                  Sri Lanka       13
25                    Algeria        5
26                       Togo        9
27                   Slovakia       12
28                  Argentina       15
29                     Angola        4
30                    Belgium       13
31                    Ecuador       15
32                      Qatar        1
33                    Lesotho        4
34                    Albania       13
35                 Madagascar       10
36                    Finland       13
37                      Ghana       15
38                    Myanmar        8
39                  Nicaragua       14
40                      Benin       12
41                       Peru       14
42               Sierra Leone       12
43                      India       14
44              United States       13
45                    Belarus       13
46                     Kuwait        3
47                      Malta        6
48                      Chile       15
49                 Tajikistan       12
50                    Croatia       13
51                    Burundi        5
52                    Bolivia       15
53                    Nigeria       13
54                      Gabon        9
55                      Italy       14
56                   Suriname        1
57                  Lithuania       15
58                     Norway       10
59                      Spain       14
60                 Mauritania       13
61           Congo (Kinshasa)        8
62   Central African Republic        5
63                    Denmark       14
64                      Niger       14
65                 Bangladesh       14
66                       Iran        8
67                    Ireland       14
68                       Laos        8
69                  Swaziland        3
70                   Thailand       15
71                     Bhutan        3
72                    Morocco        9
73                     Panama       14
74                    Ukraine       15
75                  Venezuela       11
76                    Iceland        7
77                     Israel       14
78   Taiwan Province of China        3
79                South Korea       14
80                     Cyprus       12
81                    Uruguay       15
82                     Mexico       14
83                    Estonia       14
84                    Georgia       15
85                 Montenegro       13
86                   Zimbabwe       15
87                  Indonesia       14
88                  Guatemala       14
89                   Mongolia       13
90                 Azerbaijan       14
91                      Libya        4
92                    Armenia       14
93                    Liberia        9
94                    Tunisia       11
95                   Honduras       14
96                      Syria        7
97        Trinidad and Tobago        5
98        Congo (Brazzaville)        9
99               Saudi Arabia        2
100                    Uganda       15
101                   Namibia        6
102               Switzerland       10
103                    Zambia       14
104                  Ethiopia        8
105                   Jamaica        6
106                    Latvia       14
107      United Arab Emirates        3
108                    Guinea        9
109                    Canada       14
110                Kyrgyzstan       15
111           North Macedonia       13
112                Uzbekistan        9
113            Czech Republic       11
114                Mozambique        8
115                    Belize        2
116                    Brazil       13
117                    Gambia        3
118                     Kenya       15
119                   Lebanon       13
120   Palestinian Territories        4
121                  Slovenia       13
122        Dominican Republic       15
123                  Botswana       12
124                     Japan       13
125                  Tanzania       15
126                Luxembourg       11
127               New Zealand       14
128    Bosnia and Herzegovina       13
129                     Haiti       11
130                    Poland       13
131                  Portugal       13
132                 Australia       13
133                  Cameroon       15
134                   Romania       12
135                  Bulgaria       12
136                   Austria       13
137                     Nepal       13
138                Costa Rica       14
139                     Egypt        8
140               El Salvador       15
141                Kazakhstan       15
142                    Serbia       13
143              Burkina Faso       13
144              South Africa       14
145                   Bahrain        3
146                  Colombia       15
147                   Hungary       13
148                  Pakistan       13
149                 Mauritius        7
150                   Moldova       15
151            United Kingdom       14
152                   Vietnam       10
153                      Mali       13
154               Netherlands       13

1. Filtar la columna Contry por el valor Afghanistan
2. Obtner el promedio de afecto positivo y negativo

In [ ]:
af_data = data[data['Country name'] == "Afghanistan"]

In [30]:
af_data.count()

Country name                        12
year                                12
Life Ladder                         12
Log GDP per capita                  12
Social support                      12
Healthy life expectancy at birth    12
Freedom to make life choices        12
Generosity                          12
Perceptions of corruption           12
Positive affect                     12
Negative affect                     12
dtype: int64

In [34]:
print(af_data[['Positive affect']].mean().to_frame().T)
print(af_data[['Negative affect']].mean().to_frame().T)

      Positive affect
None         0.548667
      Negative affect
None           0.3265

### Cargar dataset: world happinnes report del año 2021

1. Exploración de datos

In [35]:
data_2021 = ps.read_csv('datasets/world-happiness-report-2021.csv')
data_2021.head(4)

/Users/ale/Proyectos/envs/pyspark_env/lib/python3.11/site-packages/pyspark/pandas/utils.py:1016: PandasAPIOnSparkAdviceWarning: If `index_col` is not specified for `read_csv`, the default index is attached which can cause additional overhead.
  warnings.warn(message, PandasAPIOnSparkAdviceWarning)

  Country name Regional indicator  Ladder score  Standard error of ladder score  upperwhisker  lowerwhisker  Logged GDP per capita  Social support  Healthy life expectancy  Freedom to make life choices  Generosity  Perceptions of corruption  Ladder score in Dystopia  Explained by: Log GDP per capita  Explained by: Social support  Explained by: Healthy life expectancy  Explained by: Freedom to make life choices  Explained by: Generosity  Explained by: Perceptions of corruption  Dystopia + residual
0      Finland     Western Europe         7.842                           0.032         7.904         7.780                 10.775           0.954                     72.0                         0.949      -0.098                      0.186                      2.43                             1.446                         1.106                                  0.741                                       0.691                     0.124                                    0.481                3.253
1      Denmark     Western Europe         7.620                           0.035         7.687         7.552                 10.933           0.954                     72.7                         0.946       0.030                      0.179                      2.43                             1.502                         1.108                                  0.763                                       0.686                     0.208                                    0.485                2.868
2  Switzerland     Western Europe         7.571                           0.036         7.643         7.500                 11.117           0.942                     74.4                         0.919       0.025                      0.292                      2.43                             1.566                         1.079                                  0.816                                       0.653                     0.204                                    0.413                2.839
3      Iceland     Western Europe         7.554                           0.059         7.670         7.438                 10.878           0.983                     73.0                         0.955       0.160                      0.673                      2.43                             1.482                         1.172                                  0.772                                       0.698                     0.293                                    0.170                2.967

In [36]:
data_2021.info()

<class 'pyspark.pandas.frame.DataFrame'>
Int64Index: 149 entries, 0 to 148
Data columns (total 20 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Country name                                149 non-null    object
 1   Regional indicator                          149 non-null    object
 2   Ladder score                                149 non-null    float64
 3   Standard error of ladder score              149 non-null    float64
 4   upperwhisker                                149 non-null    float64
 5   lowerwhisker                                149 non-null    float64
 6   Logged GDP per capita                       149 non-null    float64
 7   Social support                              149 non-null    float64
 8   Healthy life expectancy                     149 non-null    float64
 9   Freedom to make life choices                149 non-null    float64
 10  Generosity                                  149 non-null    float64
 11  Perceptions of corruption                   149 non-null    float64
 12  Ladder score in Dystopia                    149 non-null    float64
 13  Explained by: Log GDP per capita            149 non-null    float64
 14  Explained by: Social support                149 non-null    float64
 15  Explained by: Healthy life expectancy       149 non-null    float64
 16  Explained by: Freedom to make life choices  149 non-null    float64
 17  Explained by: Generosity                    149 non-null    float64
 18  Explained by: Perceptions of corruption     149 non-null    float64
 19  Dystopia + residual                         149 non-null    float64
dtypes: float64(18), object(2)

### Creación de una estructura con pyspark sql
1. Definir un esquema
2. Cargar los datasets con spark
3. Aplicar el esquema para unificar
4. Convertir a pandas spark
5. Unir los dataframes con el comando concat

In [38]:
from pyspark.sql.types import StructType, StructField, StringType, IntegerType, FloatType

In [41]:
schema = StructType([
    StructField('Country', StringType(), True),
    StructField('Year', StringType(), True),
    StructField('Life_Ladder', StringType(), True),
    StructField('Log_Gdp', StringType(), True),
    StructField('Social_support', StringType(), True),
    StructField('Healthy_life_expectancy', StringType(), True),
    StructField('Freedom_to_make_life_choices', StringType(), True),
    StructField('Generosity', StringType(), True),
    StructField('Perceptions_of_corruption', StringType(), True),
    StructField('Positive_affect', StringType(), True),
    StructField('Negative_affect', StringType(), True)
])

In [42]:
data_2021_spark = spark.read.csv('datasets/world-happiness-report-2021.csv', header=True, schema=schema)
data_2021 = data_2021_spark.pandas_api()
data_2021.head(4)

25/07/18 12:55:46 WARN CSVHeaderChecker: Number of column in CSV header is not equal to number of fields in the schema:
 Header length: 20, schema size: 11
CSV file: file:///Users/ale/Proyectos/data_analysis_2/spark/pandas_api_spark/datasets/world-happiness-report-2021.csv

       Country            Year Life_Ladder Log_Gdp Social_support Healthy_life_expectancy Freedom_to_make_life_choices Generosity Perceptions_of_corruption Positive_affect Negative_affect
0      Finland  Western Europe       7.842   0.032          7.904                   7.780                       10.775      0.954                    72.000           0.949          -0.098
1      Denmark  Western Europe       7.620   0.035          7.687                   7.552                       10.933      0.954                    72.700           0.946           0.030
2  Switzerland  Western Europe       7.571   0.036          7.643                   7.500                       11.117      0.942                    74.400           0.919           0.025
3      Iceland  Western Europe       7.554   0.059          7.670                   7.438                       10.878      0.983                    73.000           0.955           0.160

In [43]:
data_spark = spark.read.csv('datasets/world-happiness-report.csv', header=True, schema=schema)
data = data_spark.pandas_api()
data.head(4)

25/07/18 12:56:59 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: Country name, year, Life Ladder, Log GDP per capita, Social support, Healthy life expectancy at birth, Freedom to make life choices, Generosity, Perceptions of corruption, Positive affect, Negative affect
 Schema: Country, Year, Life_Ladder, Log_Gdp, Social_support, Healthy_life_expectancy, Freedom_to_make_life_choices, Generosity, Perceptions_of_corruption, Positive_affect, Negative_affect
Expected: Country but found: Country name
CSV file: file:///Users/ale/Proyectos/data_analysis_2/spark/pandas_api_spark/datasets/world-happiness-report.csv

       Country  Year Life_Ladder Log_Gdp Social_support Healthy_life_expectancy Freedom_to_make_life_choices Generosity Perceptions_of_corruption Positive_affect Negative_affect
0  Afghanistan  2008       3.724   7.370          0.451                  50.800                        0.718      0.168                     0.882           0.518           0.258
1  Afghanistan  2009       4.402   7.540          0.552                  51.200                        0.679      0.190                     0.850           0.584           0.237
2  Afghanistan  2010       4.758   7.647          0.539                  51.600                        0.600      0.121                     0.707           0.618           0.275
3  Afghanistan  2011       3.832   7.620          0.521                  51.920                        0.496      0.162                     0.731           0.611           0.267

In [44]:
data.info()

25/07/18 13:00:10 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: Country name, year, Life Ladder, Log GDP per capita, Social support, Healthy life expectancy at birth, Freedom to make life choices, Generosity, Perceptions of corruption, Positive affect, Negative affect
 Schema: Country, Year, Life_Ladder, Log_Gdp, Social_support, Healthy_life_expectancy, Freedom_to_make_life_choices, Generosity, Perceptions_of_corruption, Positive_affect, Negative_affect
Expected: Country but found: Country name
CSV file: file:///Users/ale/Proyectos/data_analysis_2/spark/pandas_api_spark/datasets/world-happiness-report.csv

<class 'pyspark.pandas.frame.DataFrame'>
Int64Index: 1949 entries, 0 to 1948
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Country                       1949 non-null   object
 1   Year                          1949 non-null   object
 2   Life_Ladder                   1949 non-null   object
 3   Log_Gdp                       1913 non-null   object
 4   Social_support                1936 non-null   object
 5   Healthy_life_expectancy       1894 non-null   object
 6   Freedom_to_make_life_choices  1917 non-null   object
 7   Generosity                    1860 non-null   object
 8   Perceptions_of_corruption     1839 non-null   object
 9   Positive_affect               1927 non-null   object
 10  Negative_affect               1933 non-null   object
dtypes: object(11)

In [45]:
data_2021.info()

25/07/18 13:00:35 WARN CSVHeaderChecker: Number of column in CSV header is not equal to number of fields in the schema:
 Header length: 20, schema size: 11
CSV file: file:///Users/ale/Proyectos/data_analysis_2/spark/pandas_api_spark/datasets/world-happiness-report-2021.csv

<class 'pyspark.pandas.frame.DataFrame'>
Int64Index: 149 entries, 0 to 148
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Country                       149 non-null    object
 1   Year                          149 non-null    object
 2   Life_Ladder                   149 non-null    object
 3   Log_Gdp                       149 non-null    object
 4   Social_support                149 non-null    object
 5   Healthy_life_expectancy       149 non-null    object
 6   Freedom_to_make_life_choices  149 non-null    object
 7   Generosity                    149 non-null    object
 8   Perceptions_of_corruption     149 non-null    object
 9   Positive_affect               149 non-null    object
 10  Negative_affect               149 non-null    object
dtypes: object(11)

In [52]:
dataset = ps.concat([data, data_2021])
dataset.head(15)

25/07/18 13:12:23 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: Country name, year, Life Ladder, Log GDP per capita, Social support, Healthy life expectancy at birth, Freedom to make life choices, Generosity, Perceptions of corruption, Positive affect, Negative affect
 Schema: Country, Year, Life_Ladder, Log_Gdp, Social_support, Healthy_life_expectancy, Freedom_to_make_life_choices, Generosity, Perceptions_of_corruption, Positive_affect, Negative_affect
Expected: Country but found: Country name
CSV file: file:///Users/ale/Proyectos/data_analysis_2/spark/pandas_api_spark/datasets/world-happiness-report.csv

        Country  Year Life_Ladder Log_Gdp Social_support Healthy_life_expectancy Freedom_to_make_life_choices Generosity Perceptions_of_corruption Positive_affect Negative_affect
0   Afghanistan  2008       3.724   7.370          0.451                  50.800                        0.718      0.168                     0.882           0.518           0.258
1   Afghanistan  2009       4.402   7.540          0.552                  51.200                        0.679      0.190                     0.850           0.584           0.237
2   Afghanistan  2010       4.758   7.647          0.539                  51.600                        0.600      0.121                     0.707           0.618           0.275
3   Afghanistan  2011       3.832   7.620          0.521                  51.920                        0.496      0.162                     0.731           0.611           0.267
4   Afghanistan  2012       3.783   7.705          0.521                  52.240                        0.531      0.236                     0.776           0.710           0.268
5   Afghanistan  2013       3.572   7.725          0.484                  52.560                        0.578      0.061                     0.823           0.621           0.273
6   Afghanistan  2014       3.131   7.718          0.526                  52.880                        0.509      0.104                     0.871           0.532           0.375
7   Afghanistan  2015       3.983   7.702          0.529                  53.200                        0.389      0.080                     0.881           0.554           0.339
8   Afghanistan  2016       4.220   7.697          0.559                  53.000                        0.523      0.042                     0.793           0.565           0.348
9   Afghanistan  2017       2.662   7.697          0.491                  52.800                        0.427     -0.121                     0.954           0.496           0.371
10  Afghanistan  2018       2.694   7.692          0.508                  52.600                        0.374     -0.094                     0.928           0.424           0.405
11  Afghanistan  2019       2.375   7.697          0.420                  52.400                        0.394     -0.108                     0.924           0.351           0.502
12      Albania  2007       4.634   9.142          0.821                  65.800                        0.529     -0.009                     0.875           0.553           0.246
13      Albania  2009       5.485   9.262          0.833                  66.200                        0.525     -0.158                     0.864           0.640           0.279
14      Albania  2010       5.269   9.303          0.733                  66.400                        0.569     -0.172                     0.726           0.648           0.300